title: Daniel Issing
email: lastname DOT firstname AT gmail DOT com 
description: >-
  Global health, AI and physics
baseurl: ""
url: "https://danielissing.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Optional: Show excerpts on homepage
show_excerpts: true
